version: "3.1"

services:

  database:
    image: 'postgres:latest'
    restart: always

    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taks 

    ports:
      - "5432:5432"
