version: "3.1"

services:

  database:
    image: 'postgres:latest'
    restart: always

    environment:
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'tasks' 

    ports:
      - "5432:5432"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql